# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-18 01:58
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190812_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='avator/default.jpg', upload_to='avator/%Y%m%d/', verbose_name='用户头像'),
        ),
    ]
