# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190818_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=2, verbose_name='性别'),
        ),
    ]
