# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190818_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(3, '男'), (1, '女'), (2, '保密')], default=2, verbose_name='性别'),
        ),
    ]
