# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='歌曲名')),
                ('song_id', models.CharField(max_length=32, null=True, verbose_name='音乐id')),
                ('url', models.CharField(max_length=254, null=True, verbose_name='歌曲链接')),
                ('img', models.CharField(max_length=254, null=True, verbose_name='歌曲图片链接')),
                ('lyric', models.CharField(max_length=254, null=True, verbose_name='歌曲歌词链接')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='歌曲上线时间')),
                ('song_count', models.IntegerField(default=0, verbose_name='歌曲被点击的次数')),
            ],
            options={
                'verbose_name': '音乐库',
                'verbose_name_plural': '音乐库',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='歌手名')),
                ('img', models.CharField(max_length=254, null=True, verbose_name='歌手图片链接')),
                ('country', models.CharField(max_length=32, null=True, verbose_name='国家')),
                ('singer_mid', models.CharField(max_length=64, null=True, verbose_name='歌手id')),
            ],
            options={
                'verbose_name': '歌手表',
                'verbose_name_plural': '歌手表',
            },
        ),
        migrations.AddField(
            model_name='musicinfo',
            name='singer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repo.Singer', verbose_name='歌手'),
        ),
    ]
