# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='歌曲名')),
                ('url', models.CharField(max_length=254, null=True, verbose_name='歌曲链接')),
                ('img', models.CharField(max_length=254, null=True, verbose_name='歌曲图片链接')),
                ('lyric', models.CharField(max_length=254, null=True, verbose_name='歌曲歌词链接')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='歌曲上线时间')),
                ('song_count', models.IntegerField(default=0, verbose_name='歌曲被点击的次数')),
            ],
            options={
                'verbose_name': '音乐库',
                'verbose_name_plural': '音乐库',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='歌手名')),
            ],
            options={
                'verbose_name': '歌手表',
                'verbose_name_plural': '歌手表',
            },
        ),
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '流行'), (2, '民谣'), (3, '英语'), (4, '轻音乐')], max_length=64, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '歌曲分类',
                'verbose_name_plural': '歌曲分类',
            },
        ),
        migrations.AddField(
            model_name='musicinfo',
            name='singer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repo.Singer', verbose_name='歌手'),
        ),
        migrations.AddField(
            model_name='musicinfo',
            name='song_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.SongCategory', verbose_name='歌曲类别'),
        ),
    ]
