# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicinfo',
            name='song_class',
        ),
        migrations.AddField(
            model_name='musicinfo',
            name='song_id',
            field=models.CharField(max_length=32, null=True, verbose_name='音乐id'),
        ),
    ]
