# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='img',
            field=models.CharField(max_length=254, null=True, verbose_name='歌手图片'),
        ),
    ]
