# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_singer_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='id',
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_mid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='歌手id'),
        ),
    ]
