# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_singercollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singercollection',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_collection_set', to='repo.Singer', verbose_name='歌手'),
        ),
    ]
