# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20190820_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singercollection',
            name='status',
            field=models.BooleanField(default=False, verbose_name='收藏状态'),
        ),
    ]
