# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_auto_20190820_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='fans',
        ),
    ]
