# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 14:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0008_auto_20190820_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=254, verbose_name='评论内容')),
                ('nice', models.IntegerField(default=0, verbose_name='点赞数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modify', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_comment_set', to='repo.MusicInfo', verbose_name='音乐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_comment_set', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '歌曲评论表',
                'verbose_name_plural': '歌曲评论表',
            },
        ),
    ]
