# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0009_songcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcomments',
            name='status',
            field=models.BooleanField(default=True, verbose_name='点赞状态'),
        ),
    ]
