# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0010_songcomments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongCommentsDianZan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='点赞状态')),
            ],
            options={
                'verbose_name': '点赞表',
                'verbose_name_plural': '点赞表',
            },
        ),
        migrations.RemoveField(
            model_name='songcomments',
            name='status',
        ),
        migrations.AddField(
            model_name='songcommentsdianzan',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dianzan_set', to='repo.SongComments', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='songcommentsdianzan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dianzan_set', to=settings.AUTH_USER_MODEL, verbose_name='点赞者'),
        ),
    ]
