# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 08:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0011_auto_20190821_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicListInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='歌单名')),
                ('img', easy_thumbnails.fields.ThumbnailerImageField(default='songListimg/default.jpg', upload_to='songListimg/%Y%m%d/', verbose_name='歌单图片')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='歌单创建时间')),
                ('song', models.ManyToManyField(to='repo.MusicInfo', verbose_name='歌曲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '歌单表',
                'verbose_name_plural': '歌单表',
            },
        ),
        migrations.AlterField(
            model_name='songcomments',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_comment_set', to='repo.MusicInfo', verbose_name='歌曲'),
        ),
    ]
