# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0012_auto_20190822_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicListCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='收藏状态')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musiclist_collection_set', to='repo.MusicListInfo', verbose_name='歌单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musiclist_collection_set', to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
            ],
            options={
                'verbose_name': '歌单收藏表',
                'verbose_name_plural': '歌单收藏表',
            },
        ),
    ]
