# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0013_musiclistcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclistinfo',
            name='fans',
            field=models.IntegerField(null=True, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='singer',
            name='fans',
            field=models.IntegerField(null=True, verbose_name='粉丝数'),
        ),
    ]
