# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0015_auto_20190822_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclistinfo',
            name='fans',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='fans',
            field=models.IntegerField(default=0, verbose_name='粉丝数'),
        ),
    ]
