# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0016_auto_20190822_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicinfo',
            name='fans',
            field=models.IntegerField(default=0, verbose_name='被收藏数'),
        ),
        migrations.AlterField(
            model_name='musiclistinfo',
            name='fans',
            field=models.IntegerField(default=0, verbose_name='被收藏数'),
        ),
    ]
